version: '3.4'
services:
  test:
    container_name: test-container
    image: ${DRONE_REPO_NAME}_${DRONE_BUILD_NUMBER}
    healthcheck:
      test: curl -fL http://localhost:9091 || exit 1
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 3
